# ноутбук для проведения первичного анализа

In [1]:
import pandas as pd
import numpy as np

источник данных: https://www.consumerfinance.gov

In [2]:
df = pd.read_csv('/Users/test/Desktop/GP5/DL_project_5/data/complaints-2026-06-10_12_00.csv')
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2026-01-01T02:27:15.000Z,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,NaN,AMERIS BANCORP,GA,317XX,Servicemember,Web,2026-01-01T02:43:14.000Z,Closed with explanation,Yes,18399128
1,2026-01-01T03:23:15.000Z,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...",NaN,"Kriya Capital, LLC",GA,30297,NaN,Web,2026-01-01T03:29:57.000Z,Closed with non-monetary relief,Yes,18399338
2,2026-01-01T00:25:32.000Z,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Company has responded to the consumer and the ...,Rosebud Economic Development Corporation,TX,770XX,NaN,Web,2026-01-01T00:29:33.000Z,Closed with explanation,No,18398486
3,2026-01-01T00:12:20.000Z,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,NaN,"Portfolio Recovery Associates, LLC",TX,770XX,NaN,Web,2026-01-01T00:16:38.000Z,Closed with explanation,Yes,18398394
4,2026-01-01T00:06:38.000Z,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,NaN,"EQUIFAX, INC.",IL,60621,NaN,Web,2026-01-01T00:09:21.000Z,Closed with non-monetary relief,Yes,18398340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20T19:27:00.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,96792,NaN,Web,2026-05-20T19:31:02.000Z,Closed with explanation,Yes,22399748
53898,2026-05-20T22:59:37.000Z,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,Company has responded to the consumer and the ...,"Nationwide Capital Services, LLC",TX,75007,NaN,Web,2026-05-20T23:06:17.000Z,Closed with explanation,Yes,22409063
53899,2026-05-20T23:46:56.000Z,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",OH,448XX,NaN,Web,2026-05-21T00:08:27.000Z,Closed with explanation,Yes,22410776
53900,2026-05-20T22:10:33.000Z,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,GA,310XX,NaN,Web,2026-05-20T22:13:30.000Z,Closed with explanation,Yes,22407087
53901,2026-05-21T13:21:44.000Z,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MA,024XX,NaN,Web,2026-05-21T13:45:56.000Z,Closed with monetary relief,Yes,22426759

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53902 entries, 0 to 53901
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date received                 53902 non-null  object
 1   Product                       53902 non-null  object
 2   Sub-product                   53902 non-null  object
 3   Issue                         53902 non-null  object
 4   Sub-issue                     48859 non-null  object
 5   Consumer complaint narrative  53902 non-null  object
 6   Company public response       21709 non-null  object
 7   Company                       53902 non-null  object
 8   State                         53400 non-null  object
 9   ZIP code                      53862 non-null  object
 10  Tags                          7101 non-null   object
 11  Submitted via                 53902 non-null  object
 12  Date sent to company          53902 non-null  object
 13  Company response to consumer  53902 non-null  object
 14  Timely response?              53902 non-null  object
 15  Complaint ID                  53902 non-null  int64
dtypes: int64(1), object(15)
memory usage: 6.6+ MB

In [4]:
df.isnull().sum()

Date received                       0
Product                             0
Sub-product                         0
Issue                               0
Sub-issue                        5043
Consumer complaint narrative        0
Company public response         32193
Company                             0
State                             502
ZIP code                           40
Tags                            46801
Submitted via                       0
Date sent to company                0
Company response to consumer        0
Timely response?                    0
Complaint ID                        0
dtype: int64

In [5]:
df["Product"].value_counts()

Product
Debt collection                                        23147
Checking or savings account                            11671
Credit card                                            11373
Money transfer, virtual currency, or money service      4998
Credit reporting or other personal consumer reports     2713
Name: count, dtype: int64

In [6]:
df["Timely response?"].value_counts()

Timely response?
Yes    52978
No       924
Name: count, dtype: int64

In [8]:
df["Company response to consumer"].value_counts()

Company response to consumer
Closed with explanation            42509
Closed with non-monetary relief     6934
Closed with monetary relief         4001
Untimely response                    444
In progress                           14
Name: count, dtype: int64

In [7]:
df['Risk'] = np.where((df['Company response to consumer'] == 'Closed with monetary relief') |
    (df['Company response to consumer'] == 'Closed with non-monetary relief') |
    (df['Timely response?'] == 'No'), 1, 0)
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID,Risk
0,2026-01-01T02:27:15.000Z,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,NaN,AMERIS BANCORP,GA,317XX,Servicemember,Web,2026-01-01T02:43:14.000Z,Closed with explanation,Yes,18399128,0
1,2026-01-01T03:23:15.000Z,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...",NaN,"Kriya Capital, LLC",GA,30297,NaN,Web,2026-01-01T03:29:57.000Z,Closed with non-monetary relief,Yes,18399338,1
2,2026-01-01T00:25:32.000Z,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Company has responded to the consumer and the ...,Rosebud Economic Development Corporation,TX,770XX,NaN,Web,2026-01-01T00:29:33.000Z,Closed with explanation,No,18398486,1
3,2026-01-01T00:12:20.000Z,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,NaN,"Portfolio Recovery Associates, LLC",TX,770XX,NaN,Web,2026-01-01T00:16:38.000Z,Closed with explanation,Yes,18398394,0
4,2026-01-01T00:06:38.000Z,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,NaN,"EQUIFAX, INC.",IL,60621,NaN,Web,2026-01-01T00:09:21.000Z,Closed with non-monetary relief,Yes,18398340,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20T19:27:00.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,96792,NaN,Web,2026-05-20T19:31:02.000Z,Closed with explanation,Yes,22399748,0
53898,2026-05-20T22:59:37.000Z,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,Company has responded to the consumer and the ...,"Nationwide Capital Services, LLC",TX,75007,NaN,Web,2026-05-20T23:06:17.000Z,Closed with explanation,Yes,22409063,0
53899,2026-05-20T23:46:56.000Z,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",OH,448XX,NaN,Web,2026-05-21T00:08:27.000Z,Closed with explanation,Yes,22410776,0
53900,2026-05-20T22:10:33.000Z,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,GA,310XX,NaN,Web,2026-05-20T22:13:30.000Z,Closed with explanation,Yes,22407087,0
53901,2026-05-21T13:21:44.000Z,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MA,024XX,NaN,Web,2026-05-21T13:45:56.000Z,Closed with monetary relief,Yes,22426759,1

In [8]:
df['Risk'].value_counts()

Risk
0    42081
1    11821
Name: count, dtype: int64

In [9]:
df['Tags'].value_counts()

Tags
Servicemember                    4086
Older American                   2452
Older American, Servicemember     563
Name: count, dtype: int64

In [10]:
df["Complaint_length"] = df["Consumer complaint narrative"].str.len() # Считаем длину обращения
df["Word_count"] = df["Consumer complaint narrative"].str.split().str.len() # Считаем количество слов в обращении
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID,Risk,Complaint_length,Word_count
0,2026-01-01T02:27:15.000Z,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,NaN,AMERIS BANCORP,GA,317XX,Servicemember,Web,2026-01-01T02:43:14.000Z,Closed with explanation,Yes,18399128,0,1002,188
1,2026-01-01T03:23:15.000Z,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...",NaN,"Kriya Capital, LLC",GA,30297,NaN,Web,2026-01-01T03:29:57.000Z,Closed with non-monetary relief,Yes,18399338,1,2039,332
2,2026-01-01T00:25:32.000Z,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Company has responded to the consumer and the ...,Rosebud Economic Development Corporation,TX,770XX,NaN,Web,2026-01-01T00:29:33.000Z,Closed with explanation,No,18398486,1,530,85
3,2026-01-01T00:12:20.000Z,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,NaN,"Portfolio Recovery Associates, LLC",TX,770XX,NaN,Web,2026-01-01T00:16:38.000Z,Closed with explanation,Yes,18398394,0,430,74
4,2026-01-01T00:06:38.000Z,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,NaN,"EQUIFAX, INC.",IL,60621,NaN,Web,2026-01-01T00:09:21.000Z,Closed with non-monetary relief,Yes,18398340,1,182,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20T19:27:00.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,96792,NaN,Web,2026-05-20T19:31:02.000Z,Closed with explanation,Yes,22399748,0,272,39
53898,2026-05-20T22:59:37.000Z,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,Company has responded to the consumer and the ...,"Nationwide Capital Services, LLC",TX,75007,NaN,Web,2026-05-20T23:06:17.000Z,Closed with explanation,Yes,22409063,0,231,39
53899,2026-05-20T23:46:56.000Z,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",OH,448XX,NaN,Web,2026-05-21T00:08:27.000Z,Closed with explanation,Yes,22410776,0,2281,434
53900,2026-05-20T22:10:33.000Z,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,GA,310XX,NaN,Web,2026-05-20T22:13:30.000Z,Closed with explanation,Yes,22407087,0,1704,277
53901,2026-05-21T13:21:44.000Z,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MA,024XX,NaN,Web,2026-05-21T13:45:56.000Z,Closed with monetary relief,Yes,22426759,1,851,137

In [11]:
df["Date received"] = pd.to_datetime(df["Date received"])
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID,Risk,Complaint_length,Word_count
0,2026-01-01 02:27:15+00:00,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,NaN,AMERIS BANCORP,GA,317XX,Servicemember,Web,2026-01-01T02:43:14.000Z,Closed with explanation,Yes,18399128,0,1002,188
1,2026-01-01 03:23:15+00:00,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...",NaN,"Kriya Capital, LLC",GA,30297,NaN,Web,2026-01-01T03:29:57.000Z,Closed with non-monetary relief,Yes,18399338,1,2039,332
2,2026-01-01 00:25:32+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Company has responded to the consumer and the ...,Rosebud Economic Development Corporation,TX,770XX,NaN,Web,2026-01-01T00:29:33.000Z,Closed with explanation,No,18398486,1,530,85
3,2026-01-01 00:12:20+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,NaN,"Portfolio Recovery Associates, LLC",TX,770XX,NaN,Web,2026-01-01T00:16:38.000Z,Closed with explanation,Yes,18398394,0,430,74
4,2026-01-01 00:06:38+00:00,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,NaN,"EQUIFAX, INC.",IL,60621,NaN,Web,2026-01-01T00:09:21.000Z,Closed with non-monetary relief,Yes,18398340,1,182,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20 19:27:00+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,96792,NaN,Web,2026-05-20T19:31:02.000Z,Closed with explanation,Yes,22399748,0,272,39
53898,2026-05-20 22:59:37+00:00,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,Company has responded to the consumer and the ...,"Nationwide Capital Services, LLC",TX,75007,NaN,Web,2026-05-20T23:06:17.000Z,Closed with explanation,Yes,22409063,0,231,39
53899,2026-05-20 23:46:56+00:00,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",OH,448XX,NaN,Web,2026-05-21T00:08:27.000Z,Closed with explanation,Yes,22410776,0,2281,434
53900,2026-05-20 22:10:33+00:00,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,GA,310XX,NaN,Web,2026-05-20T22:13:30.000Z,Closed with explanation,Yes,22407087,0,1704,277
53901,2026-05-21 13:21:44+00:00,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MA,024XX,NaN,Web,2026-05-21T13:45:56.000Z,Closed with monetary relief,Yes,22426759,1,851,137

In [12]:
df["month"] = df["Date received"].dt.month
df["day_of_week"] = df["Date received"].dt.day_name()
df["hour"] = df["Date received"].dt.hour
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,...,Date sent to company,Company response to consumer,Timely response?,Complaint ID,Risk,Complaint_length,Word_count,month,day_of_week,hour
0,2026-01-01 02:27:15+00:00,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,NaN,AMERIS BANCORP,GA,317XX,...,2026-01-01T02:43:14.000Z,Closed with explanation,Yes,18399128,0,1002,188,1,Thursday,2
1,2026-01-01 03:23:15+00:00,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...",NaN,"Kriya Capital, LLC",GA,30297,...,2026-01-01T03:29:57.000Z,Closed with non-monetary relief,Yes,18399338,1,2039,332,1,Thursday,3
2,2026-01-01 00:25:32+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Company has responded to the consumer and the ...,Rosebud Economic Development Corporation,TX,770XX,...,2026-01-01T00:29:33.000Z,Closed with explanation,No,18398486,1,530,85,1,Thursday,0
3,2026-01-01 00:12:20+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,NaN,"Portfolio Recovery Associates, LLC",TX,770XX,...,2026-01-01T00:16:38.000Z,Closed with explanation,Yes,18398394,0,430,74,1,Thursday,0
4,2026-01-01 00:06:38+00:00,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,NaN,"EQUIFAX, INC.",IL,60621,...,2026-01-01T00:09:21.000Z,Closed with non-monetary relief,Yes,18398340,1,182,31,1,Thursday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20 19:27:00+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,96792,...,2026-05-20T19:31:02.000Z,Closed with explanation,Yes,22399748,0,272,39,5,Wednesday,19
53898,2026-05-20 22:59:37+00:00,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,Company has responded to the consumer and the ...,"Nationwide Capital Services, LLC",TX,75007,...,2026-05-20T23:06:17.000Z,Closed with explanation,Yes,22409063,0,231,39,5,Wednesday,22
53899,2026-05-20 23:46:56+00:00,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",OH,448XX,...,2026-05-21T00:08:27.000Z,Closed with explanation,Yes,22410776,0,2281,434,5,Wednesday,23
53900,2026-05-20 22:10:33+00:00,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,GA,310XX,...,2026-05-20T22:13:30.000Z,Closed with explanation,Yes,22407087,0,1704,277,5,Wednesday,22
53901,2026-05-21 13:21:44+00:00,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MA,024XX,...,2026-05-21T13:45:56.000Z,Closed with monetary relief,Yes,22426759,1,851,137,5,Thursday,13

In [13]:
cols_to_drop = [
    "Date sent to company",
    "Company response to consumer",
    "Timely response?",
    "Complaint ID",
    "ZIP code"
]
df = df.drop(columns=cols_to_drop)
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,Tags,Submitted via,Risk,Complaint_length,Word_count,month,day_of_week,hour
0,2026-01-01 02:27:15+00:00,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,NaN,AMERIS BANCORP,GA,Servicemember,Web,0,1002,188,1,Thursday,2
1,2026-01-01 03:23:15+00:00,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...",NaN,"Kriya Capital, LLC",GA,NaN,Web,1,2039,332,1,Thursday,3
2,2026-01-01 00:25:32+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Company has responded to the consumer and the ...,Rosebud Economic Development Corporation,TX,NaN,Web,1,530,85,1,Thursday,0
3,2026-01-01 00:12:20+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,NaN,"Portfolio Recovery Associates, LLC",TX,NaN,Web,0,430,74,1,Thursday,0
4,2026-01-01 00:06:38+00:00,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,NaN,"EQUIFAX, INC.",IL,NaN,Web,1,182,31,1,Thursday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20 19:27:00+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,NaN,Web,0,272,39,5,Wednesday,19
53898,2026-05-20 22:59:37+00:00,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,Company has responded to the consumer and the ...,"Nationwide Capital Services, LLC",TX,NaN,Web,0,231,39,5,Wednesday,22
53899,2026-05-20 23:46:56+00:00,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",OH,NaN,Web,0,2281,434,5,Wednesday,23
53900,2026-05-20 22:10:33+00:00,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,GA,NaN,Web,0,1704,277,5,Wednesday,22
53901,2026-05-21 13:21:44+00:00,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MA,NaN,Web,1,851,137,5,Thursday,13

In [14]:
cols_to_drop1 = [
    "Submitted via",
    "Tags"
]
df = df.drop(columns=["Submitted via", "Tags"])
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,Risk,Complaint_length,Word_count,month,day_of_week,hour
0,2026-01-01 02:27:15+00:00,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,NaN,AMERIS BANCORP,GA,0,1002,188,1,Thursday,2
1,2026-01-01 03:23:15+00:00,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...",NaN,"Kriya Capital, LLC",GA,1,2039,332,1,Thursday,3
2,2026-01-01 00:25:32+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Company has responded to the consumer and the ...,Rosebud Economic Development Corporation,TX,1,530,85,1,Thursday,0
3,2026-01-01 00:12:20+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,NaN,"Portfolio Recovery Associates, LLC",TX,0,430,74,1,Thursday,0
4,2026-01-01 00:06:38+00:00,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,NaN,"EQUIFAX, INC.",IL,1,182,31,1,Thursday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20 19:27:00+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,0,272,39,5,Wednesday,19
53898,2026-05-20 22:59:37+00:00,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,Company has responded to the consumer and the ...,"Nationwide Capital Services, LLC",TX,0,231,39,5,Wednesday,22
53899,2026-05-20 23:46:56+00:00,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",OH,0,2281,434,5,Wednesday,23
53900,2026-05-20 22:10:33+00:00,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,GA,0,1704,277,5,Wednesday,22
53901,2026-05-21 13:21:44+00:00,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MA,1,851,137,5,Thursday,13

In [15]:
df.isnull().sum()

Date received                       0
Product                             0
Sub-product                         0
Issue                               0
Sub-issue                        5043
Consumer complaint narrative        0
Company public response         32193
Company                             0
State                             502
Risk                                0
Complaint_length                    0
Word_count                          0
month                               0
day_of_week                         0
hour                                0
dtype: int64

In [16]:
df = df.drop('Company public response', axis=1)
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company,State,Risk,Complaint_length,Word_count,month,day_of_week,hour
0,2026-01-01 02:27:15+00:00,Checking or savings account,Checking account,Managing an account,Deposits and withdrawals,I mobile deposited a XXXX check to Ameris Bank...,AMERIS BANCORP,GA,0,1002,188,1,Thursday,2
1,2026-01-01 03:23:15+00:00,Debt collection,I do not know,Attempts to collect debt not owed,Debt was result of identity theft,"Credence Resource Management , LLC ( Use the a...","Kriya Capital, LLC",GA,1,2039,332,1,Thursday,3
2,2026-01-01 00:25:32+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,"Help my rights are being violated, 15 U.S.C. 1...",Rosebud Economic Development Corporation,TX,1,530,85,1,Thursday,0
3,2026-01-01 00:12:20+00:00,Debt collection,I do not know,Took or threatened to take negative or legal a...,Threatened or suggested your credit would be d...,This company is violating my rights they have ...,"Portfolio Recovery Associates, LLC",TX,0,430,74,1,Thursday,0
4,2026-01-01 00:06:38+00:00,Credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,My information was heisted and this accounts a...,"EQUIFAX, INC.",IL,1,182,31,1,Thursday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20 19:27:00+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information is missing that should be on the r...,My credit reports are inaccurate. These inaccu...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,0,272,39,5,Wednesday,19
53898,2026-05-20 22:59:37+00:00,Debt collection,Other debt,Threatened to contact someone or share informa...,Talked to a third-party about your debt,I received a very shady voicemail from structu...,"Nationwide Capital Services, LLC",TX,0,231,39,5,Wednesday,22
53899,2026-05-20 23:46:56+00:00,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,In XXXX of XXXX I was charged for a Best Buy r...,"CITIBANK, N.A.",OH,0,2281,434,5,Wednesday,23
53900,2026-05-20 22:10:33+00:00,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt is not yours,"My name is XXXX XXXX, residing at XXXX XXXX XX...",WELLS FARGO & COMPANY,GA,0,1704,277,5,Wednesday,22
53901,2026-05-21 13:21:44+00:00,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Card was charged for something you did not pur...,I am the victim of a persistent household-wide...,"CITIBANK, N.A.",MA,1,851,137,5,Thursday,13

In [21]:
df = df.drop(columns=['Sub-product', 'Sub-issue'])
df

,Date received,Product,Issue,Consumer complaint narrative,Company,State,Risk,Complaint_length,Word_count,month,day_of_week,hour
0,2026-01-01 02:27:15+00:00,Checking or savings account,Managing an account,I mobile deposited a XXXX check to Ameris Bank...,AMERIS BANCORP,GA,0,1002,188,1,Thursday,2
1,2026-01-01 03:23:15+00:00,Debt collection,Attempts to collect debt not owed,"Credence Resource Management , LLC ( Use the a...","Kriya Capital, LLC",GA,1,2039,332,1,Thursday,3
2,2026-01-01 00:25:32+00:00,Debt collection,Took or threatened to take negative or legal a...,"Help my rights are being violated, 15 U.S.C. 1...",Rosebud Economic Development Corporation,TX,1,530,85,1,Thursday,0
3,2026-01-01 00:12:20+00:00,Debt collection,Took or threatened to take negative or legal a...,This company is violating my rights they have ...,"Portfolio Recovery Associates, LLC",TX,0,430,74,1,Thursday,0
4,2026-01-01 00:06:38+00:00,Credit card,Getting a credit card,My information was heisted and this accounts a...,"EQUIFAX, INC.",IL,1,182,31,1,Thursday,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20 19:27:00+00:00,Credit reporting or other personal consumer re...,Incorrect information on your report,My credit reports are inaccurate. These inaccu...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,0,272,39,5,Wednesday,19
53898,2026-05-20 22:59:37+00:00,Debt collection,Threatened to contact someone or share informa...,I received a very shady voicemail from structu...,"Nationwide Capital Services, LLC",TX,0,231,39,5,Wednesday,22
53899,2026-05-20 23:46:56+00:00,Credit card,Problem with a purchase shown on your statement,In XXXX of XXXX I was charged for a Best Buy r...,"CITIBANK, N.A.",OH,0,2281,434,5,Wednesday,23
53900,2026-05-20 22:10:33+00:00,Debt collection,Attempts to collect debt not owed,"My name is XXXX XXXX, residing at XXXX XXXX XX...",WELLS FARGO & COMPANY,GA,0,1704,277,5,Wednesday,22
53901,2026-05-21 13:21:44+00:00,Credit card,Problem with a purchase shown on your statement,I am the victim of a persistent household-wide...,"CITIBANK, N.A.",MA,1,851,137,5,Thursday,13

In [22]:
df.isnull().sum()

Date received                     0
Product                           0
Issue                             0
Consumer complaint narrative      0
Company                           0
State                           502
Risk                              0
Complaint_length                  0
Word_count                        0
month                             0
day_of_week                       0
hour                              0
dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53902 entries, 0 to 53901
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date received                 53902 non-null  datetime64[ns, UTC]
 1   Product                       53902 non-null  object
 2   Issue                         53902 non-null  object
 3   Consumer complaint narrative  53902 non-null  object
 4   Company                       53902 non-null  object
 5   State                         53400 non-null  object
 6   Risk                          53902 non-null  int64
 7   Complaint_length              53902 non-null  int64
 8   Word_count                    53902 non-null  int64
 9   month                         53902 non-null  int32
 10  day_of_week                   53902 non-null  object
 11  hour                          53902 non-null  int32
dtypes: datetime64[ns, UTC](1), int32(2), int64(3), object(6)
memory usage: 4.5+ MB

In [27]:
df[df.duplicated(keep=False)]

,Date received,Product,Issue,Consumer complaint narrative,Company,State,Risk,Complaint_length,Word_count,month,day_of_week,hour
25382,2026-02-25 18:38:22+00:00,Debt collection,Attempts to collect debt not owed,I am disputing this account as inaccurate and ...,ENCORE CAPITAL GROUP INC.,CA,0,762,131,2,Wednesday,18
25901,2026-02-25 18:38:22+00:00,Debt collection,Attempts to collect debt not owed,I am disputing this account as inaccurate and ...,ENCORE CAPITAL GROUP INC.,CA,0,762,131,2,Wednesday,18
28303,2026-03-04 14:50:19+00:00,Debt collection,Attempts to collect debt not owed,I am disputing this account as inaccurate and ...,"Spring Oaks Capital, LLC",IL,1,763,131,3,Wednesday,14
28360,2026-03-04 14:50:19+00:00,Debt collection,Attempts to collect debt not owed,I am disputing this account as inaccurate and ...,"Spring Oaks Capital, LLC",IL,1,763,131,3,Wednesday,14
37273,2026-03-19 14:33:00+00:00,Debt collection,Took or threatened to take negative or legal a...,This company is violating my rights they have ...,United Revenue Corporation,TX,0,175,33,3,Thursday,14
37449,2026-03-19 14:33:00+00:00,Debt collection,Took or threatened to take negative or legal a...,This company is violating my rights they have ...,United Revenue Corporation,TX,0,175,33,3,Thursday,14
38465,2026-03-24 03:15:19+00:00,Debt collection,Took or threatened to take negative or legal a...,This company is violating my rights they have ...,"Kinum, Inc., Indianapolis, IN Branch",IN,0,180,33,3,Tuesday,3
38735,2026-03-24 03:15:19+00:00,Debt collection,Took or threatened to take negative or legal a...,This company is violating my rights they have ...,"Kinum, Inc., Indianapolis, IN Branch",IN,0,180,33,3,Tuesday,3

In [29]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
df.groupby("Risk")["Word_count"].mean()

Risk
0    202.717144
1    215.261421
Name: Word_count, dtype: float64

In [31]:
df['Issue'].value_counts()

Issue
Attempts to collect debt not owed                                  12106
Managing an account                                                 6592
Written notification about debt                                     3973
Problem with a purchase shown on your statement                     3915
False statements or representation                                  3119
Took or threatened to take negative or legal action                 2049
Incorrect information on your report                                1911
Problem with a lender or other company charging your account        1748
Closing an account                                                  1597
Fraud or scam                                                       1526
Other features, terms, or problems                                  1440
Fees or interest                                                    1395
Getting a credit card                                               1086
Communication tactics                                               1054
Improper use of your report                                          899
Unauthorized transactions or other transaction problem               897
Opening an account                                                   849
Other transaction problem                                            838
Closing your account                                                 821
Problem caused by your funds being low                               801
Problem with a company's investigation into an existing problem      719
Problem when making payments                                         647
Advertising and marketing, including promotional offers              583
Trouble accessing funds in your mobile or digital wallet             559
Electronic communications                                            524
Trouble using your card                                              505
Money was not available when promised                                342
Threatened to contact someone or share information improperly        318
Managing, opening, or closing your mobile wallet account             243
Struggling to pay your bill                                          135
Confusing or missing disclosures                                     134
Other service problem                                                115
Unexpected or other fees                                              79
Problem with customer service                                         75
Wrong amount charged or received                                      59
Credit monitoring or identity theft protection services               50
Problem with fraud alerts or security freezes                         45
Confusing or misleading advertising or marketing                      43
Lost or stolen money order                                            43
Problem adding money                                                  32
Unable to get your credit report or credit score                      18
Overdraft, savings, or rewards features                               12
Problem with a company's investigation into an existing issue          1
Incorrect exchange rate                                                1
Name: count, dtype: int64

In [36]:
top_issues = (df["Issue"].value_counts().head(10).index)
top_issues

Index(['Attempts to collect debt not owed', 'Managing an account',
       'Written notification about debt',
       'Problem with a purchase shown on your statement',
       'False statements or representation',
       'Took or threatened to take negative or legal action',
       'Incorrect information on your report',
       'Problem with a lender or other company charging your account',
       'Closing an account', 'Fraud or scam'],
      dtype='object', name='Issue')

In [42]:
df["Issue"] = (df["Issue"].apply(lambda x: x if x in top_issues else "Other"))
df

,Date received,Product,Issue,Consumer complaint narrative,Company,State,Risk,Complaint_length,Word_count,month,day_of_week,hour
0,2026-01-01 02:27:15+00:00,Checking or savings account,Managing an account,I mobile deposited a XXXX check to Ameris Bank...,AMERIS BANCORP,GA,0,1002,188,1,Thursday,2
1,2026-01-01 03:23:15+00:00,Debt collection,Attempts to collect debt not owed,"Credence Resource Management , LLC ( Use the a...","Kriya Capital, LLC",GA,1,2039,332,1,Thursday,3
2,2026-01-01 00:25:32+00:00,Debt collection,Took or threatened to take negative or legal a...,"Help my rights are being violated, 15 U.S.C. 1...",Rosebud Economic Development Corporation,TX,1,530,85,1,Thursday,0
3,2026-01-01 00:12:20+00:00,Debt collection,Took or threatened to take negative or legal a...,This company is violating my rights they have ...,"Portfolio Recovery Associates, LLC",TX,0,430,74,1,Thursday,0
4,2026-01-01 00:06:38+00:00,Credit card,Other,My information was heisted and this accounts a...,"EQUIFAX, INC.",IL,1,182,31,1,Thursday,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2026-05-20 19:27:00+00:00,Credit reporting or other personal consumer re...,Incorrect information on your report,My credit reports are inaccurate. These inaccu...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,0,272,39,5,Wednesday,19
53898,2026-05-20 22:59:37+00:00,Debt collection,Other,I received a very shady voicemail from structu...,"Nationwide Capital Services, LLC",TX,0,231,39,5,Wednesday,22
53899,2026-05-20 23:46:56+00:00,Credit card,Problem with a purchase shown on your statement,In XXXX of XXXX I was charged for a Best Buy r...,"CITIBANK, N.A.",OH,0,2281,434,5,Wednesday,23
53900,2026-05-20 22:10:33+00:00,Debt collection,Attempts to collect debt not owed,"My name is XXXX XXXX, residing at XXXX XXXX XX...",WELLS FARGO & COMPANY,GA,0,1704,277,5,Wednesday,22
53901,2026-05-21 13:21:44+00:00,Credit card,Problem with a purchase shown on your statement,I am the victim of a persistent household-wide...,"CITIBANK, N.A.",MA,1,851,137,5,Thursday,13

In [41]:
df['Issue'].value_counts()

Issue
Other                                                           15362
Attempts to collect debt not owed                               12106
Managing an account                                              6592
Written notification about debt                                  3973
Problem with a purchase shown on your statement                  3915
False statements or representation                               3119
Took or threatened to take negative or legal action              2049
Incorrect information on your report                             1911
Problem with a lender or other company charging your account     1748
Closing an account                                               1597
Fraud or scam                                                    1526
Name: count, dtype: int64

Задача 1) По тексту жалобы классифицировать к какому финансовому продукту относится 

Вход: Consumer complaint narrative

Выход: Product

Классы: 
Debt collection
Checking or savings account
Credit card
Money transfer, virtual currency, or money service
Credit reporting or other personal consumer reports

Задача 2) По характеристикам жалобы предсказать риск обращения 

Вход: 
Product
Sub-product
Issue
Sub-issue
Company
State
Complaint_length
Word_count
month	
day_of_week	
hour

Выход:
Risk (Risk = 0 -> Closed with explanation) (Risk = 1 -> Closed with monetary relief/Closed with non-monetary relief/Timely response = No)

Цель: Оценить обычная жалоба или Потенциально проблемная жалоба

In [44]:
df_nlp_product = df[["Consumer complaint narrative", "Product"]].copy()
df_nlp_issue = df[["Consumer complaint narrative", 'Issue']].copy()
df_nlp_product

,Consumer complaint narrative,Product
0,I mobile deposited a XXXX check to Ameris Bank...,Checking or savings account
1,"Credence Resource Management , LLC ( Use the a...",Debt collection
2,"Help my rights are being violated, 15 U.S.C. 1...",Debt collection
3,This company is violating my rights they have ...,Debt collection
4,My information was heisted and this accounts a...,Credit card
...,...,...
53897,My credit reports are inaccurate. These inaccu...,Credit reporting or other personal consumer re...
53898,I received a very shady voicemail from structu...,Debt collection
53899,In XXXX of XXXX I was charged for a Best Buy r...,Credit card
53900,"My name is XXXX XXXX, residing at XXXX XXXX XX...",Debt collection
53901,I am the victim of a persistent household-wide...,Credit card

In [45]:
df_nlp_product.to_csv(
    "/Users/test/Desktop/GP5/DL_project_5/data/nlp_product_dataset.csv",
    index=False
)

In [46]:
df_nlp_issue.to_csv(
    "/Users/test/Desktop/GP5/DL_project_5/data/nlp_issue_dataset.csv",
    index=False
)

In [49]:
df_mlp = df[
    [
        "Product",
        "Issue",
        "Company",
        "State",
        "Complaint_length",
        "Word_count",
        "month",
        "day_of_week",
        "hour",
        "Risk"
    ]
].copy()
df_mlp

,Product,Issue,Company,State,Complaint_length,Word_count,month,day_of_week,hour,Risk
0,Checking or savings account,Managing an account,AMERIS BANCORP,GA,1002,188,1,Thursday,2,0
1,Debt collection,Attempts to collect debt not owed,"Kriya Capital, LLC",GA,2039,332,1,Thursday,3,1
2,Debt collection,Took or threatened to take negative or legal a...,Rosebud Economic Development Corporation,TX,530,85,1,Thursday,0,1
3,Debt collection,Took or threatened to take negative or legal a...,"Portfolio Recovery Associates, LLC",TX,430,74,1,Thursday,0,0
4,Credit card,Other,"EQUIFAX, INC.",IL,182,31,1,Thursday,0,1
...,...,...,...,...,...,...,...,...,...,...
53897,Credit reporting or other personal consumer re...,Incorrect information on your report,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",HI,272,39,5,Wednesday,19,0
53898,Debt collection,Other,"Nationwide Capital Services, LLC",TX,231,39,5,Wednesday,22,0
53899,Credit card,Problem with a purchase shown on your statement,"CITIBANK, N.A.",OH,2281,434,5,Wednesday,23,0
53900,Debt collection,Attempts to collect debt not owed,WELLS FARGO & COMPANY,GA,1704,277,5,Wednesday,22,0
53901,Credit card,Problem with a purchase shown on your statement,"CITIBANK, N.A.",MA,851,137,5,Thursday,13,1

In [51]:
df_mlp.to_csv(
    "/Users/test/Desktop/GP5/DL_project_5/data/mlp_dataset.csv",
    index=False
)